### ISSUE TITLE
Interest in NCO support for UGRID-2D?

### ISSUE THREAD

**Issue by czender** [ugrid-conventions/ugrid-conventions#14]
Hi Rich et al.,
NCO 4.5.0 supports regridding to/from some unstructured grids given a SCRIP/ESMF remap file, and I'm interested in extending this support to more grids in 4.5.1, now in development. How do UGRID users currently regrid their data? Do you use ESMF_RegridWeightGen? Are there other tools that you use that generate regrid weights for UGRID-compliant files? Might you use NCO to regrid your data if it supported UGRID and, if so, what would "support UGRID" mean to you? Feedback on any/all of these questions would be appreciated. Strictly 2D for now.
Best,
Charlie

**Comment by czender** [comment]
Am closing this due to underwhelming response :) FYI NCO since version 4.6.6 supports writing full-featured 2D UGRID meshfiles for rectangular-lat-lon grids, see [docs](http://nco.sf.net/nco.html#ugrid).

**Comment by ChrisBarker-NOAA** [comment]
Thanks for your interest! Maybe we'll keep this in mind if we get people asking for re-gridding tools.

**Comment by pletzer** [comment]
For the next generation weather/climate model LFRic, we at the National Institute for Water and Atmospheric research (NIWA) are currently looking into extending bilinear and conservative interpolation methods for staggered grids with field values attached to cell edges and faces (aka Arakawa C/D grids). 

Anyone interested in seeing u,v,w fields interpolated on UGRIDs? 

Would be able to conserve line or flux integrals. Shoot me an email at alexander dot pletzer at niwa dot co dot nz if you'd like this to be implemented.

**Comment by ChrisBarker-NOAA** [comment]
I am! -- I've sent you a note offline.
