### ISSUE TITLE
Time to bump to 1.0?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [ugrid-conventions/ugrid-conventions#24]
At least some folks are using the standard -- can't we call it 1.0?

Maybe after: #23 is merged.

**Comment by rsignell-usgs** [comment]
:+1:   we can't be whimpy forever

**Comment by ChrisBarker-NOAA** [comment]
OK -- I'm looking at the issues we left hanging to see if anything else needs to be done.

then I say we bumb.

**Comment by svater** [comment]
So this should be closed now, right?

**Comment by ocefpaf** [comment]
Yep.
