### ISSUE TITLE
Edge and face physical locations are ambiguous?

### ISSUE THREAD

**Issue by djkirkham** [ugrid-conventions/ugrid-conventions#40]
It's not currently specified where in physical space edges and faces are to be located. Assuming an edge is intended to be a straight line on and ellipsoid/sphere (which https://github.com/ugrid-conventions/ugrid-conventions/issues/33 proposed clarifying), and ignoring the cases where there are an infinite number of possibilities, it's still ambiguous whether it is the shorter or longer of these lines. And adopting the convention that it is always the shortest seems restrictive.

**Comment by hrajagers** [comment]
Dear Daniel,

The initial aim of UGRID was to define the mesh topology and to offer a
framework in which further conventions could be developed.
My impression is that people with whom I have had contact are happy with
the description in #33
<https://github.com/ugrid-conventions/ugrid-conventions/issues/33>.
In most projected coordinate systems applied for models the straight line
is well defined (this excludes interrupted projections such as Goode
Homolosine).
However, you are right by stating that there are still two options in
spherical coordinates (following the shortest and longest distance along
the great-circle).
So far chosing the shortest seems to be appropriate in all cases that I've
encountered.
Why do consider that convention to be restrictive?

In the context of 1D applications we have come across the necessity to be
able to prescribe a more tortuous edge between nodes.
In that case we have started to refer to netCDF-CF-simple-geometry
<https://github.com/twhiteaker/netCDF-CF-simple-geometry> for the edge
geometry. However, this would be quite some overhead for 2D (or even 3D)
meshes.
I would like to first see an application that needs it, before we start
defining exceptions.

Best regards,

Bert

**Comment by ChrisBarker-NOAA** [comment]
This is a challenge faced by ALL specs in the spatial world. I can't find it at the moment, but there is a nice discussion about GEOJSON that talks about it -- but coming to no good conclusion. However, there is this in the GeoJSON spec:

https://tools.ietf.org/html/rfc7946#page-14

```
5.2.  The Antimeridian

   Consider a set of point Features within the Fiji archipelago,
   straddling the antimeridian between 16 degrees S and 20 degrees S.
   The southwest corner of the box containing these Features is at 20
   degrees S and 177 degrees E, and the northwest corner is at 16
   degrees S and 178 degrees W.  The antimeridian-spanning GeoJSON
   bounding box for this FeatureCollection is

   "bbox": [177.0, -20.0, -178.0, -16.0]

   and covers 5 degrees of longitude.

   The complementary bounding box for the same latitude band, not
   crossing the antimeridian, is

   "bbox": [-178.0, -20.0, 177.0, -16.0]

   and covers 355 degrees of longitude.

   The latitude of the northeast corner is always greater than the
   latitude of the southwest corner, but bounding boxes that cross the
   antimeridian have a northeast corner longitude that is less than the
   longitude of the southwest corner.
```
that works because they have defined a "bounding box" as being specified by the southwest and northeast corner, rather than simply an grid aligned rectangle.

I wonder if we could do something similar? not sure, as grid cells are not generally aligned with lat-lon lines. But maybe one could say that the first point of a cell is, say, the southwest-most point??? That may conflict with other point numbering schemes, though :-)

**Comment by ChrisBarker-NOAA** [comment]
As to @hrajagers's point -- I agree. Remember that the convention is designed to support model meshes, not arbitrary geometries -- and i"m having a hard time imagining a model mesh that would have a cell spanning the long way around the earth! (though maybe near the pole?? 

So I suggest we say that, at least by default, that two nodes are connected the short way.

Then if and when someone comes up with a use-case for the alternative, we provide a way to define it.

Additions to the text are welcome!

**Comment by ChrisBarker-NOAA** [comment]
@hrajagers: since you seem to be online right now, could you take a look at #41 and merge if you don't see any issues? Minor change, but a step forward...

**Comment by djkirkham** [comment]
Thanks for your responses.

I agree that defining an edge going the long way round is unlikely to come up in the real world. Maybe I'm being a bit overzealous in my desire for flexibility! I'm happy to assume edges go the short way.

Thanks!

**Comment by ChrisBarker-NOAA** [comment]
It would still be good to say that explicitly in the convention doc.
