### ISSUE TITLE
example files?

### ISSUE THREAD

**Issue by nschloe** [ugrid-conventions/ugrid-conventions#62]
I'm thinking about implementing this format in my I/O package. Are there any example files that I could play around with?

**Comment by erogluorhan** [comment]
Hi Nico, we are implementing [UXarray](https://github.com/UXARRAY/uxarray) to support analysis/visualization on native UGRIDs; I think you might find it helpful to see it.  See also [Project Raijin](https://raijin.ucar.edu/). Feel free to reach out with anything!

We have some UGRID file samples in [here](https://github.com/UXARRAY/uxarray/tree/main/test/meshfiles) as well; see the README.md file in that directory for info. [This](https://github.com/UXARRAY/uxarray/files/8336834/grid.nc.gz) is another UGRID file.

**Comment by nschloe** [comment]
Alright, thanks.

What's ugrid's suffix? ug, nc, nc.gz?

**Comment by ChrisBarker-NOAA** [comment]
plain old .nc -- they are netcdf files.

I suppose it would be nice to have a convention for a suffix, such as `*.ug.nc`, but I think keeping the nc is probably important for a lot of tools that expect it.

You may also want to look at gridded -- though we've been pretty bad about compliant examples[*]:

https://github.com/NOAA-ORR-ERD/gridded

[*] The challenge for us with gridded is that our primary use case is being able to read and work with a wide range of model outputs, and many (most) operational models' output aren't UGRID compliant -- at least they weren't back when we started all that.

**Comment by nschloe** [comment]
> I suppose it would be nice to have a convention for a suffix, such as *.ug.nc, but I think keeping the nc is probably important for a lot of tools that expect it.

Almost all mesh formats use NetCDF, HDF, or other data formats internally without exposing it in the file name suffix. Exodus, XDMF, MED are examples.

In my opinion, this makes sense too. The suffix `.nc` could be _anything_. When specifying `.ug`, the computer knows it's UGRID, i.e., NetCDF with a particular set of fields. I'd recommend endorsing a custom suffix.
