### ISSUE TITLE
Trying to add any basemap like etopo map in ugrid.plot.pcolormesh plot

### ISSUE THREAD

**Issue by shihab-saran** [ugrid-conventions/ugrid-conventions#73]
I have succesfully plotted Water Level output from Delft3D FM. But I could not find a way how I can plot the waterlevel on top of a basemap. As, I am using ugrid,plot() in this case. I will appreciate it if anyone kindly give me a solution.

**Comment by ChrisBarker-NOAA** [comment]
I think you are in the wrong project here -- this is for maintaining the conventions, not for any tools for working with them.

Try asking on a forum for the plotting tool(s) you are using.
