### ISSUE TITLE
Data associated with mesh?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [ugrid-conventions/ugrid-conventions#8]
As it stands, the standard covers how to specify the mesh, but not how to specify data associated with the mesh. But of course, the whole point is to actually have data on the mesh.

I propose that variable that store dat associated with the mesh have the following required attributes:

```
data_var:mesh = "the_name_of_the_associated_mesh";
data_var:location = "node"
```

Where the mesh attribute specifies the mesh name -- this would be the name of the variable defining the mesh structure (the one with cf_role = "mesh_topology"). This is required as there can be more than one mesh in a file.

The "location" attribute specifies where on the mesh the data are located: "node", "edge", "face", or "boundary" (or "volume") for 3-d). You could probably deduce this by looking at the dimensions, but that seems fragile and unclear.

There could be a "coordinates" attribute, that would reference the coordinates, etc variables as well -- though I think that should be optional.

In addition, they would of course carry the usual CF attributes: units, standard_name, etc, etc.

thoughts?

**Comment by ChrisBarker-NOAA** [comment]
So this was about data associated with the grid, but as of this discussion:

https://github.com/pyugrid/pyugrid/issues/109

I finally wrote this PR: #23 

So we seem to have locked down that any order is OK. Does the doc need updating in any way?

**Comment by hrajagers** [comment]
Yes, I believe most people seem to agree that we should allow for arbitrary dimension order. This is just like the free order of the "face_node_connectivity" arrays which may be either 3 x nFaces or nFaces x 3 for triangles. I would suggest to add the following text:

The order of dimensions on a data variable is arbitrary, so nTimeSteps x nLayers x nFaces, nTimeSteps x nFaces x nLayers, nFaces x nLayers x nTimeSeps, etc would all be valid. In line with CF/COARDS and OGC NetCDF-CF we recommend to use the T,Z,Y,X [c order notation] order as much as possible where the unstructured horizontal dimension should be read for Y,X. That is, the order nTimeSteps x nLayers x nFaces [c order notation] is recommended: the nFaces is the fastest increasing dimension, then the nLayers, and finally the nTimeSteps.

**Comment by ChrisBarker-NOAA** [comment]
Thanks @hrajagers: added to the version being discussed in #23
